ifeq ($(OS), Windows_NT)
	PLATFORM := win-64
else
	uname := $(shell sh -c 'uname 2>/dev/null || echo unknown')
	ifeq ($(uname), Darwin)
		PLATFORM := osx-64
	else ifeq ($(uname), Linux)
		PLATFORM := linux-64
	else
		@echo "Unsupported platform"
		exit 1
	endif
endif

all:
	@echo "Detected platform: $(PLATFORM)"

# -- Dependency management with PDM --------------------------------------------

# Lock PDM dependencies
pdm-lock:
	pdm lock

.PHONY: pdm-lock

# -- Dependency management with Conda ------------------------------------------

# Lock conda dependencies
conda-lock:
	conda-lock lock --mamba \
		--file pyproject.toml
		--lockfile requirements/conda-lock.yml

# Initialise development environment
conda-init:
	conda-lock install --mamba --name {{ python_conda_env_name }} requirements/conda-lock.yml
	python3 -m pip install --editable . --no-deps

# Shortcut for PDM and conda lock
lock: conda-lock-all pdm-lock

conda-update: conda-lock-all conda-init lock

.PHONY: conda-lock conda-lock-all conda-init conda-update

# -- Testing -------------------------------------------------------------------

test:
	nox --no-venv -s test

nox-test:
	nox -s test

.PHONY: test nox-test

# -- Documentation -------------------------------------------------------------

docs:
	pdm run sphinx-build -b html docs docs/_build/html
	@echo "Access documentation at docs/_build/html/index.html"

.PHONY: docs

# -- Build ---------------------------------------------------------------------

build:
	pdm build

dist-clean:
	rm -rf build dist

publish: build
	pdm publish

.PHONY: build dist-clean publish
