.DEFAULT_GOAL := help
SHELL := bash

DUTY = $(shell [ -n "${VIRTUAL_ENV}" ] || echo pdm run) duty

args = $(foreach a,$($(subst -,_,$1)_args),$(if $(value $a),$a="$($a)"))
check_quality_args = files
docs_serve_args = host port
release_args = version
test_args = match

DUTIES = \
	changelog \
	check-dependencies \
	clean \
	coverage \
	docs \
	{%- if repository_provider == "github.com" %}
	docs-deploy \
	{%- endif %}
	docs-regen \
	docs-serve \
	format \
	release \
	test \
	nox-test


.PHONY: help
help:
	@$(DUTY) --list

.PHONY: lock
lock:
	@pdm lock

.PHONY: setup
setup:
	@bash scripts/setup.sh

.PHONY: check
check:
	@$(DUTY) check-quality check-types check-docs
	@$(DUTY) check-dependencies

.PHONY: $(DUITES)
$(DUITES):
	@$(DUTY) $@ $(call args,$@)
