.DEFAULT_GOAL := help
SHELL := bash

DUTY = $(shell [ -n "${VIRTUAL_ENV}" ] || echo pdm run) duty

{# args = $(foreach a,$($(subst -,_,$1)_args),$(if $(value $a),$a="$($a)"))
check_quality_args = files
docs_serve_args = host port
release_args = version
test_args = match #}

DUTIES = \
	clean \
	coverage \
	docs \
	docs-serve \
	format \
	test \
	nox-test


.PHONY: help
help:
	@$(DUTY) --list

.PHONY: lock
lock:
	@pdm lock

.PHONY: setup
setup:
	@bash scripts/setup.sh

.PHONY: $(DUTIES)
$(DUTIES):
	{# @$(DUTY) $@ $(call args,$@) #}
	@$(DUTY) $@
